### ISSUE TITLE
Nginx Ingress Annotations Not Applied

### ISSUE THREAD

**Issue by Janaka-Steph** [openfaas-incubator/ingress-operator#28] opened 2020-05-28 11:31 UTC
Adding `nginx.ingress.kubernetes.io/from-to-www-redirect: "true"` annotations to FunctionIngress resources has no effect.

## Context
My function is a website that uses the dockerfile template and is served with Nginx. I am wondering if this Nginx is causing the annotation to not be applied

## Expected Behaviour
Expect annotations to be applied.

## Steps to Reproduce (for bugs)
Adding `from-to-www-redirect` annotation.
```
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: example
  namespace: openfaas
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
...
```
`kubectl apply -f fn_ingress.yml`

Note that I can see the annotation on functioningress resource.
```
$ kubectl describe functioningress.openfaas.com/example -n openfaas
Name:         example
Namespace:    openfaas
Labels:       <none>
Annotations:  nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
```

And also in the ingress resource. 
```
$ kubectl describe ing -n openfaas                                             
Name:             example
Namespace:        openfaas
...
Annotations:     cert-manager.io/issuer: letsencrypt-prod
                      com.openfaas.spec: {"metadata":{"name":"example","namespace":"openfaas"...
                      kubernetes.io/ingress.class: nginx
                      nginx.ingress.kubernetes.io/from-to-www-redirect: true
                      nginx.ingress.kubernetes.io/rewrite-target: /function/example/$1
```

## Your Environment
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alexellis** [comment] 2020-05-28 11:36
Hi @Janaka-Steph thank you for putting together a detailed report. This is much appreciated.

Would you be willing to work on a patch for this?

Regards,

Alex

**Comment by alexellis** [comment] 2020-05-28 11:37
I would probably suggest you use an alternative to `rewrite-target`, perhaps what you shared on Slack? The reason for this is that we do set specific rules for URL re-writing according to the way the FunctionIngress has been created.

**Comment by Janaka-Steph** [comment] 2020-05-28 11:52
Ok I have modified the issue, sorry for the confusion. Hope it is clear now.
I would love to be able to contribute and patch it but I don't think my skills are good enough. :/

**Comment by aledbf** [comment] 2020-05-28 13:14
@Janaka-Steph please post the ingress yaml. What are you trying to do?

This annotation only creates a new server block with a redirect. If the ingress host is www.foo.bar, it will create a server block with `server_name foo.bar` and any request to this host triggers a redirect to `www.foo.bar`

**Comment by Janaka-Steph** [comment] 2020-05-28 13:28
@aledbf Thanks for the quick reply. I am hosting a website, which works well except I just need to redirect to www.

The ingress has been posted in the issue, but I here is to whole file. Or are you referring to an other file?
```
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: example
  namespace: openfaas
spec:
  domain: "example.com"
  function: "example"
  ingressType: "nginx"
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-prod"
      kind: "Issuer"
```

**Comment by alexellis** [comment] 2020-05-28 13:48
Post the `Ingress` YAML that was generated for you - that's the language @aledbf will be more used to seeing. FunctionIngress is just a wrapper on that.

**Comment by alexellis** [comment] 2020-05-28 14:02
I created a fix for this in #29, but the code is already present @Janaka-Steph - I imagine that you're doing something wrong, because there are unit tests which show that custom annotations of the FNI are copied to the Ingress record?

**Closed** 2020-05-28 14:44 UTC

**Comment by Janaka-Steph** [comment] 2020-05-28 16:35
After more digging, I think that even though we can see the annotation with `kubectl describe functioningress.openfaas.com/example -n openfaas` and `kubectl describe ing -n openfaas `, I can't see any server block with redirect in nginx.conf.
I check the nginx.conf with `$ kubectl -n default exec ingress-nginx-controller-5b4bf5bc7b-9ptxm -- cat /etc/nginx/nginx.conf`
Please reopen the issue.

**Comment by alexellis** [comment] 2020-05-28 16:39
There's no need to reopen the issue in my opinion since the **annotation is being applied** to the Ingress definition being created. Whether or not that annotation does what you expect is another matter. Have I missed something?

**Comment by Janaka-Steph** [comment] 2020-05-28 16:47
I don't follow you. Maybe I should open an issue on Nginx-Ingress then? 
But the goal is to have the annotation actually creating the proper config obviously.

**Comment by alexellis** [comment] 2020-05-28 17:16
The issue was "my custom annotation from the FunctionIngress wasn't inserted on my ingress record" - it turns out that _it was_ and I mistakenly created a patch, even when it was working and the behaviour was already present. That's my bad.

Now if we are outputting the correct annotation (and we are, that's been confirmed now) on the Ingress record, then you need to take it up with the ingress-nginx developers. There is no issue with the OpenFaaS IngressOperator AFAIK.
